use customer_behavior;

SELECT * FROM customer_behavior.customers;

describe customers;

-- 1. Total revenue generated by gender
select gender, sum(purchase_amount) as revenue
from customers
group by gender;

-- 2. Customers who used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customers
where discount_applied = 'Yes'
	and purchase_amount >= (
		select avg(purchase_amount)
		from customers
	);

-- 3. Top 5 products with the highest average review rating?
select  item_purchased, round(avg(review_rating), 2) as 'Average Product Rating'
from customers
group by item_purchased
order by 'Average Product Rating' desc
limit 5;

-- 4. Compare the average Purchase Amounts between Shipping. Types
select shipping_type, round(avg(purchase_amount), 2) as 'Average spend'
from customers
where shipping_type in ('Standard', 'Express', '2-Day Shipping', 'Free Shipping', 'Next Day Air', 'Store Pickup')
group by shipping_type;

-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(AVG(purchase_amount), 2) as avg_spend,
SUM(purchase_amount) as total_revenue
from customers
group by subscription_status
order by total_revenue desc;

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
		-- ROUND (100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
		count(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;

-- 7. Segment customers into New, Returning, and Loyal; based on their total number of previous purchases, and show the count of each segment.
select
	case
		when previous_purchases between 0 and 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
		else 'Loyal'
	end as customer_segment,
    count(*) as 'No. of Customers',
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM customers), 2) AS segment_percentage
from customers
group by customer_segment;

-- 8. Top 3 most purchased products within each category?
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
) ranked_items
WHERE item_rank <= 3;

-- variant
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
		count(customer_id) as repeat_buyers
from customers
where previous_purchases > 5
group by subscription_status;

-- 10. Revenue contribution of each age group?
select age_group, sum(purchase_amount) as revenue
from customers
group by age_group
order by revenue desc